apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-giropops
  name: pod-giropops
spec:
  containers:
  - image: nginx
    name: pod-giropops
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi" 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
