apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-giropops
  name: pod-giropops
spec:
  containers:
  - image: nginx
    name: pod-giropops
    ports:
    - containerPort: 80
    volumeMounts:
    - name: meu-pvc
      mountPath: /usr/share/nginx/html
  volumes:
  - name: meu-pvc
    persistentVolumeClaim:
      claimName: meu-pvc
