apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: nginx-replicaset
  name: nginx-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-replicaset
  template:
    metadata:
      labels:
        app: nginx-replicaset
    spec:
       containers:
       - image: nginx:1.19.1
         name: nginx
         resources:
           limits:
             cpu: 0.3
             memory: 256Mi
           requests:
             cpu: 0.3
             memory: 64Mi
